### ISSUE TITLE
data retrieving error

### ISSUE THREAD

**Issue by NazgulCoder** [jolantahuba/YT-Backup#1]
hey
![image](https://user-images.githubusercontent.com/85739956/181914976-cdbf2fba-f6ac-46c7-859d-b4ea48ce145f.png)
im having this issue when selfhosting it, i tried with 2 different webhosts + locally deploying it but still the same error happens, while on your hosted version i can download my playlists normally without any problem

thanks in advance for your help :)

**Comment by jolantahuba** [comment]
Hello,
it is probably problem with an API key restriction. I restricted API key to my github domain only, so you can't use this key in your own. You will need to generate your own Youtube API key and change it in the code. :)

**Comment by NazgulCoder** [comment]
perfect, it works!! i was exactly searching for something like this because due to YouTube i lost 4 playlists for a total of 3000+ songs :(

If i can give a suggestion for a next update (i am shit at coding web languages) would be great the support with some Cronjobs to daily create backups and alert you whether some videos have been deleted/set private

**Comment by jolantahuba** [comment]
I'm glad I could help :)
Thank you very much for suggestion - cool and interesting idea. I will learn about it more, but I'm quite newbie in coding yet, so it may take a while to build something more interesting. Anyway, I will do my best to try something like this in the future :)

**Comment by NazgulCoder** [comment]
Cronjob can be done through the webhost to daily run code of a PHP page (an idea could be to store in some txt files the youtube playlists you are overwatching, and then the PHP page runs the JS code, the cronjob just does it automatically every 24h)

just giving ideas :)

**Comment by jolantahuba** [comment]
Very appreciate :) Thank you for the tips
