### ISSUE TITLE
[Question] what's the meaning if we can't restore the deleted video

### ISSUE THREAD

**Issue by roeniss** [jolantahuba/YT-Backup#5]
Hi, I'm curious about the goal/usecase of this project.

Backing metadata up is so cool but what's the meaning in that? What's your motivation for this project?

**Comment by jolantahuba** [comment]
Hello,
Originally, I just wanted to write down somewhere the titles and authors of the videos or songs that I like.
It would not restore the content, but if you have the titles or authors of the videos, maybe you can find the same video, song or artist on the other platforms or social media (if it's gone from YouTube). You can try to 'google' it, or even find something similar.
(... and I guess I just like to have my data somewhere in the basic files, just in case 😄)

There are also another great tools I have discovered later, for restoring or just finding some information about the lost content:
- https://archive.org/web/
- https://www.recovermy.video/ (for YouTube specifically)

Thank you for interesting question, and I hope this would help you :)

**Comment by roeniss** [comment]
@jolantahuba I understood. Have a nice day!
